version: '3'
services:
  ray_flask_app:
    build:
      context: ..   # The parent directory is now the context
      dockerfile: docker/Dockerfile
    ports:
      - "5010:5010" # Expose Flask app port
    environment:
      - PYTHONPATH=/usr/src/app
    volumes:
      - ./src/config.yaml:/app/config.yaml
